name: Deploy Rogue One OS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de lancer le déploiement manuellement depuis l'onglet Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Build & Test Client
      - name: Install, Type-check & Build Client
        run: |
          cd client
          npm install
          npm run type-check
          npm run build
          cd ..

      # 2. Type-check & Test Server
      - name: Install, Type-check & Test Server
        run: |
          cd server
          npm install
          npm run type-check
          npm run test
          cd ..

      # 2. Préparation de la clé SSH pour le transfert
      - name: Setup SSH
        run: |
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      # 3. Transfert du Serveur (le contenu de /server vers la racine du VPS)
      - name: Rsync Server Files
        run: |
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            --exclude 'node_modules' \
            --exclude 'storage' \
            --exclude 'db.sqlite' \
            --exclude '.git' \
            ./server/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/

      # 4. Création du dossier client/dist sur le VPS et transfert du Build
      - name: Rsync Client Build
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ${{ secrets.VPS_PATH }}/client/dist"
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            ./client/dist/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/client/dist/

      # 5. Installation des dépendances et redémarrage PM2
      - name: Restart Server via SSH
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.VPS_PATH }}
            
            # Installation des